# -*- coding: utf-8 -*-
import sys;
import argparse;
import re;

def main():
    parser = argparse.ArgumentParser(description="melanite color scheme applier");
    parser.add_argument("--prefix", metavar="STR", help="prefix for replacement", default=r"@melanite-");
    parser.add_argument("--scheme", metavar="TSV", required=True, help="scheme tsv (generated by melanite-generate.py)");
    opt = parser.parse_args();

    d = dict(map(lambda c, v: ( c, v ), *zip(*map(lambda x: x.rstrip("\n").split("\t"), open(opt.scheme)))));

    re_melanite = re.compile(re.escape(opt.prefix) + r"([\-\w]+)");
    for line in map(lambda line: line.rstrip("\n"), sys.stdin):
        line = re_melanite.sub(lambda m: d[m.group(1)], line);
        print(line);

    sys.exit(0);

if (__name__=="__main__"):
    main();
